version: "3"

services:
  ipfs-cluster:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001" # IPFS Swarm port
      - "5001:5001" # IPFS API port
      - "8080:8080" # IPFS Gateway port
    volumes:
      - ./data:/data/ipfs # Mount a local directory for IPFS data persistence
